theme: jekyll-theme-cayman
title: A Historical, Governmental, and Statistical Overview of Maine's Political History
name: Jack Olcott
bio: "I am a student researcher at Bowdoin College working with Professor Jack O'Brien on this prokect
email: jolcott@bowdoin.edu
linkedin: www.linkedin.com/in/jack-olcott 
